### ISSUE TITLE
Release current master on NPM

### ISSUE THREAD

**Issue by dpoindexter** [Zenwolf/babel-plugin-dev#3]
I'd love to use this plugin with our Babel 6 build process, and it looks like the code in master has been updated for Babel 6. The version released on NPM doesn't have these updates, though. Any concerns with bumping the version and releasing?

**Comment by Zenwolf** [comment]
Not sure why I did not see this notification earlier, but I will publish this tonight!

**Comment by Zenwolf** [comment]
Published! Thanks!
